#!/bin/sh

WHERE=/tmp/bin
test -d $WHERE/.limit || mkdir -p $WHERE/.limit
mountpoint $WHERE || mount -t tmpfs -o size=10M tmpfs $WHERE
chown -R nobody $WHERE
CLOCKDIR=/home/nisim/web/bin
exec </dev/null
exec 2>&1
exec /busybox/httpd -f \
  -c $CLOCKDIR/httpd.conf \
  -h $CLOCKDIR/public \
  -u nobody \
  -p 8899
