#!/bin/sh

test -d /tmp/bin || mkdir /tmp/bin
mountpoint /tmp/bin || mount -t tmpfs -o size=10M tmpfs /tmp/bin
chown -R nobody /tmp/bin
CLOCKDIR=/home/nisim/web/bin
exec </dev/null
exec 2>&1
exec /busybox/httpd -f \
  -c $CLOCKDIR/httpd.conf \
  -h $CLOCKDIR/public \
  -u nobody \
  -p 127.0.0.1:8899
